### ISSUE TITLE
Build and Run 64-bit Arm Yocto Linux image on Qemu

### ISSUE THREAD

**Issue by SimonW29** [ArmDeveloperEcosystem/arm-learning-paths#680] opened 2024-01-09 18:34 UTC
I am trying to run this learning path on a Raspberry Pi400 with Ubuntu 22.04.
There is at least 100Gbytes of free storage
I successfully follow all the step I reach 'bitbake' - when I get failures, so far, building libgcrypt, opkg-utils and openssl-native. What is likely to be wrong?

I note that the branch in the web page is 4.0.6 where the current version in the yocto project is 4.0.15. Is this going to be significant? What is the CLI to change to the new branch?

**Comment by jasonrandrews** [comment] 2024-01-10 13:44
Hi @SimonW29 
I will check out the instructions on Ubuntu 22.04 on Arm. I think most users have been doing it on non-Arm host machines, so there may be something different. I will also check the newest version. 
Thanks for reporting the trouble you are having.

**Comment by SimonW29** [comment] 2024-01-10 18:07
Hi Jason

I think it might have been caused by the Pi crashing - not sure why it has, but switching to 4.0.15 causes a new build to start - no cached output - that crashed after about 520 tasks. The first build crashed in a similar place - not the same place though.

Restarting the hardware and rerunning bitbake, it starts again without redoing the 520 odd tasks. Build is now failing again, but on a different task.

Where do I go to delete any files associated with the failed task to get it to do just that one clean without redoing all 500?

Simon

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jasonrandrews** [comment] 2024-01-10 18:48
Hello @SimonW29 

I wasn't able to reproduce any problems on Arm systems. I don't have Pi 400 but tried similar Cortex-A72 boards running Ubuntu 22.04 

To clean your build, you can remove the `build-qemu-arm64` directory and follow the steps again by running `source oe-init-build-env build-qemu-arm64` and then `sed -i '/qemuarm64/s/^#//g' conf/local.conf`. This will give you a new config and you can build using `bitbake core-image-minimal`. 

Looks like you figured out to substitute 15 for 6 if you want version 4.0.15

**Comment by SimonW29** [comment] 2024-01-11 21:13
Thank you Jason

I've made some progress. The Pi400 isn't an ideal platform. It only has 4GBytes of RAM. The Image of Ubuntu 22.04 provided by https://www.raspberrypi.com/software/ works out of the box. However, it is configured with only 1Gbytes of swap memory. With only 5Gbytes total RAM the build runs out of memory and crashes. Restarting after that is unpredictable. Changing SWAP size to 8Gbytes - and enabling SS state build mirrors (uncomment in config) allows build to complete in about 4 hours. The result works.

I'll re-try building without SS Mirrors, and if using USB rather than uSD storage to see the difference in success and time. I think it would be viable to use an original Pi4 or Pi5 with 8Gbytes of RAM.

**Comment by jasonrandrews** [comment] 2024-01-16 16:21
@SimonW29 I'm going to close this issue. I don't see any problems with the instructions, but the build is certainly challenging in terms of disk space, processing performance, and memory.

**Closed by jasonrandrews** 2024-01-16 16:21 UTC
